"""Validate the archived Figure 2c comparator MAT and export its tables.
No model is fitted. Source defaults to the packaged figure data; output must
be written to a separate directory using --output-dir.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import csv
import sys

import numpy as np
from scipy.io import loadmat, savemat

MODEL_NAMES = ["ACeT", "Ridge", "SVR", "Random forest"]
SUFFIXES = ["transformer", "ridge", "svr", "rf"]

EXPECTED = {
    "test_r2_all": np.array([0.7409, 0.5265, 0.5360, 0.4787]),
    "test_rmse_all": np.array([4.7663, 6.4434, 6.3782, 6.7604]),
    "test_mae_all": np.array([3.0832, 5.0883, 4.2363, 4.6130]),
    "cv_r2_mean": np.array([0.6210, 0.5328, 0.4350, 0.6780]),
    "cv_rmse_mean": np.array([6.2002, 7.0101, 7.7953, 5.7044]),
    "cv_mae_mean": np.array([4.2097, 5.5395, 5.3117, 3.9728]),
}

REQUIRED_KEYS = [
    "cv_r2_transformer", "cv_r2_ridge", "cv_r2_svr", "cv_r2_rf",
    "cv_rmse_transformer", "cv_rmse_ridge", "cv_rmse_svr", "cv_rmse_rf",
    "cv_mae_transformer", "cv_mae_ridge", "cv_mae_svr", "cv_mae_rf",
    "test_r2_all", "test_rmse_all", "test_mae_all",
]


def as_vector(mat: dict, key: str) -> np.ndarray:
    if key not in mat:
        raise KeyError(f"Required variable missing from source MAT: {key}")
    arr = np.asarray(mat[key], dtype=float).reshape(-1)
    return arr


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "data/figure2c_corrected_baselines.mat",
        help="Corrected source MAT generated by the minimal fold-specific baseline rerun.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory for the standardized Figure 2c files.",
    )
    parser.add_argument(
        "--tolerance",
        type=float,
        default=0.01,
        help="Allowed absolute difference from the approved summary values.",
    )
    args = parser.parse_args()

    source = args.source.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    if not source.exists():
        raise FileNotFoundError(
            f"Corrected source MAT was not found:\n{source}\n\n"
            "Supply the packaged source MAT through --source."
        )

    mat = loadmat(source)
    missing = [key for key in REQUIRED_KEYS if key not in mat]
    if missing:
        raise KeyError(f"Missing required MAT variables: {missing}")

    cv = {}
    for metric in ["r2", "rmse", "mae"]:
        cv[metric] = np.column_stack(
            [as_vector(mat, f"cv_{metric}_{suffix}") for suffix in SUFFIXES]
        )
        if cv[metric].shape != (5, 4):
            raise ValueError(
                f"Expected cv_{metric} shape (5,4), got {cv[metric].shape}"
            )

    test_r2 = as_vector(mat, "test_r2_all")
    test_rmse = as_vector(mat, "test_rmse_all")
    test_mae = as_vector(mat, "test_mae_all")
    for name, arr in [
        ("test_r2_all", test_r2),
        ("test_rmse_all", test_rmse),
        ("test_mae_all", test_mae),
    ]:
        if arr.shape != (4,):
            raise ValueError(f"Expected {name} length 4, got {arr.shape}")

    observed = {
        "test_r2_all": test_r2,
        "test_rmse_all": test_rmse,
        "test_mae_all": test_mae,
        "cv_r2_mean": cv["r2"].mean(axis=0),
        "cv_rmse_mean": cv["rmse"].mean(axis=0),
        "cv_mae_mean": cv["mae"].mean(axis=0),
    }

    validation_lines = [
        f"Source MAT: {source}",
        "Expected model order: ACeT, Ridge, SVR, Random forest",
        "",
    ]
    all_pass = True
    for key, expected in EXPECTED.items():
        actual = observed[key]
        delta = np.abs(actual - expected)
        passed = bool(np.all(delta <= args.tolerance))
        all_pass &= passed
        validation_lines.append(
            f"{key}: {'PASS' if passed else 'FAIL'}\n"
            f"  actual   = {np.array2string(actual, precision=6)}\n"
            f"  expected = {np.array2string(expected, precision=6)}\n"
            f"  max |difference| = {delta.max():.6f}"
        )

    if not all_pass:
        report_path = output_dir / "figure2c_validation_report.txt"
        report_path.write_text("\n\n".join(validation_lines) + "\n", encoding="utf-8")
        raise ValueError(
            "The source MAT does not match the approved corrected Figure 2c summary. "
            f"See {report_path}"
        )

    out_mat = output_dir / "figure2c_corrected_baselines.mat"
    savemat(
        out_mat,
        {
            "model_names": np.array(MODEL_NAMES, dtype=object),
            "cv_r2": cv["r2"],
            "cv_rmse": cv["rmse"],
            "cv_mae": cv["mae"],
            "cv_r2_transformer": cv["r2"][:, 0],
            "cv_r2_ridge": cv["r2"][:, 1],
            "cv_r2_svr": cv["r2"][:, 2],
            "cv_r2_rf": cv["r2"][:, 3],
            "cv_rmse_transformer": cv["rmse"][:, 0],
            "cv_rmse_ridge": cv["rmse"][:, 1],
            "cv_rmse_svr": cv["rmse"][:, 2],
            "cv_rmse_rf": cv["rmse"][:, 3],
            "cv_mae_transformer": cv["mae"][:, 0],
            "cv_mae_ridge": cv["mae"][:, 1],
            "cv_mae_svr": cv["mae"][:, 2],
            "cv_mae_rf": cv["mae"][:, 3],
            "test_r2_all": test_r2,
            "test_rmse_all": test_rmse,
            "test_mae_all": test_mae,
            "cv_r2_mean": cv["r2"].mean(axis=0),
            "cv_r2_sd": cv["r2"].std(axis=0, ddof=1),
            "cv_rmse_mean": cv["rmse"].mean(axis=0),
            "cv_rmse_sd": cv["rmse"].std(axis=0, ddof=1),
            "cv_mae_mean": cv["mae"].mean(axis=0),
            "cv_mae_sd": cv["mae"].std(axis=0, ddof=1),
            "source_mat": np.array([str(source)], dtype=object),
        },
    )

    fold_csv = output_dir / "figure2c_corrected_fold_metrics.csv"
    with fold_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Model", "Fold", "CV_R2", "CV_RMSE", "CV_MAE"])
        for model_idx, model in enumerate(MODEL_NAMES):
            for fold in range(5):
                writer.writerow(
                    [
                        model,
                        fold + 1,
                        f"{cv['r2'][fold, model_idx]:.9f}",
                        f"{cv['rmse'][fold, model_idx]:.9f}",
                        f"{cv['mae'][fold, model_idx]:.9f}",
                    ]
                )

    summary_csv = output_dir / "figure2c_corrected_summary.csv"
    with summary_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "Model",
                "CV_R2_mean", "CV_R2_SD",
                "CV_RMSE_mean", "CV_RMSE_SD",
                "CV_MAE_mean", "CV_MAE_SD",
                "Test_R2", "Test_RMSE", "Test_MAE",
            ]
        )
        for i, model in enumerate(MODEL_NAMES):
            writer.writerow(
                [
                    model,
                    f"{cv['r2'][:, i].mean():.9f}",
                    f"{cv['r2'][:, i].std(ddof=1):.9f}",
                    f"{cv['rmse'][:, i].mean():.9f}",
                    f"{cv['rmse'][:, i].std(ddof=1):.9f}",
                    f"{cv['mae'][:, i].mean():.9f}",
                    f"{cv['mae'][:, i].std(ddof=1):.9f}",
                    f"{test_r2[i]:.9f}",
                    f"{test_rmse[i]:.9f}",
                    f"{test_mae[i]:.9f}",
                ]
            )

    validation_lines.extend(
        [
            "",
            "VALIDATION PASSED.",
            f"Standardized MAT: {out_mat}",
            f"Fold metrics CSV: {fold_csv}",
            f"Summary CSV: {summary_csv}",
            "No model training was performed.",
        ]
    )
    report_path = output_dir / "figure2c_validation_report.txt"
    report_path.write_text("\n\n".join(validation_lines) + "\n", encoding="utf-8")

    print(report_path.read_text(encoding="utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
